### ISSUE TITLE
paper.md,README: need a statement of need

### ISSUE THREAD

**Issue by kortschak** [iferres/phylen#11]
This is for https://github.com/openjournals/joss-reviews/issues/593.

A review criterion is a statement of need: "Do the authors clearly state what problems the software is designed to solve and who the target audience is?"

Can you please make a clearer statement to this effect in paper.md and README.md.

**Comment by giraola** [comment]
We have expanded the last paragraph (before Acknowledgements section) to better explain what problems the software is designed to solve and who is the target audience.

**Comment by kortschak** [comment]
In 52b5058209852ee76ac1ff8ab7096525d3cee21a `s/Phylen is unique as integrates the highly accessed EggNOG database/Phylen is unique as it integrates the highly accessed EggNOG database/` (missing "it").

**Comment by giraola** [comment]
Corrected.

**Comment by kortschak** [comment]
Thanks
