### ISSUE TITLE
Please add list of dependencies needed for installation

### ISSUE THREAD

**Issue by kortschak** [iferres/phylen#7]
In assessing whether the package satisfies the installability criterion for https://github.com/openjournals/joss-reviews/issues/593 I ran into a small road bump (I don't use phangorn, which is why this arose).

The install process halted with an error in installing igraph because of a lack of libxml2-dev on my system. It would be helpful for users if you provided a list of required system packages for each of the supported platforms since the R build systems are pretty unhelpful in pointing users in the right direction when things like this happen.

**Comment by iferres** [comment]
Hi @kortschak . Sorry for the delay answering this thread. I found other people have had the same problem with the igraph package installation. I added a paragraph at README.md pointing out the igraph system requirements. Thanks for the note.

By the way, could you finally install and test the functionality of phylen?

**Comment by kortschak** [comment]
Thank you, that addresses it.

Yes, I' managed to install the software, but I was waiting for unit tests before I go ahead an look at functionality. I'll hopefully get to that over the next week.
