### ISSUE TITLE
Please add community guidelines documentation

### ISSUE THREAD

**Issue by kortschak** [iferres/phylen#8]
For https://github.com/openjournals/joss-reviews/issues/593, can you please add something that satisfies "Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support"

A CONTRIBUTING.md and text in the README.md would be the best IMO.

**Comment by iferres** [comment]
Added CODE_OF_CONDUCT.md, CONTRIBUTING.md and some text at README.md . Do you think it's ok? @kortschak

**Comment by kortschak** [comment]
That looks good to me. Thanks.
