### ISSUE TITLE
README: figure 1A shows 4 nodes in a 3 taxon alignment

### ISSUE THREAD

**Issue by kortschak** [iferres/phylen#9]
This is for https://github.com/openjournals/joss-reviews/issues/593, and is a bit of phylogenetic pedantry on my part.

Can you change the figure 1A to either show a simple 3 taxon star tree or, preferably, add a fourth taxon to the figure to make the tree interesting.

**Comment by giraola** [comment]
We have updated the figure.

**Comment by kortschak** [comment]
It looks like the png file was deleted in the repo rather than modified, leaving the link in the paper broken.

**Comment by kortschak** [comment]
Strictly speaking it is still not a possible inference from the hypothetical input data as the rooting requires an out group, but its really just pedantry on my part, so I'll leave this since it's really only intended to be illustrative.
